# Generated by Django 5.1.5 on 2025-03-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostGrad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('n_pront', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['tipos'],
            },
        ),
        migrations.CreateModel(
            name='Presos',
            fields=[
                ('number_doc', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_full', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='presos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institutions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='presos.institution')),
                ('posto_grad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postgrad', to='presos.postgrad')),
                ('state_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='presos.states')),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_docs', to='presos.tipo_documento')),
            ],
            options={
                'ordering': ['name_full'],
            },
        ),
    ]
