# Generated by Django 5.1.5 on 2025-03-26 19:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_oficios', models.CharField(max_length=100)),
                ('n_sei', models.CharField(max_length=50)),
                ('orgao', models.CharField(max_length=50)),
                ('date_send', models.DateField()),
                ('descricao', models.TextField()),
                ('tipo_prisao', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'fechada'), ('SEMIABERTA', 'Semiaberta'), ('HARMONIZADA', 'Harmonizada'), ('PREVENTIVA', 'Preventiva'), ('TEMPORARIA', 'Temporária'), ('OUTROS', 'Outros')], max_length=50)),
                ('anexos', models.FileField(blank=True, null=True, upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_pront_presos', models.ManyToManyField(related_name='oficioss', to='presos.presos')),
            ],
        ),
        migrations.CreateModel(
            name='OficiosPresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_oficios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_oficio', to='oficios.oficios')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_presos', to='presos.presos')),
            ],
        ),
    ]
