# Generated by Django 5.1.7 on 2025-04-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0002_oficios_modified_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OficiosPresos',
        ),
    ]
